version: '3.7'


services:
  luna:
    tty: true
    image: junofx/luna:0.1.0
    environment:
      BUDDY: fin
    env_file:
      - .env
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ./docs:/app/docs
      - ./tests:/app/tests
      - ./src/luna:/app/luna
      - ./Makefile:/app/Makefile
      - ./htmlcov:/app/htmlcov
      - ./README.md:/app/README.md
      - /var/run/docker.sock:/var/run/docker.sock:ro

  workstation:
    tty: true
    image: nginx
    environment:
      LUNA: fin
